### ISSUE TITLE
Add a load testing section

### ISSUE THREAD

**Issue by mbland** [18F/testing-cookbook#24]
Can probably start stealing from 18F/college-choice-data#7, maybe even lure @dnesting into drafting, or at least contributing or reviewing.

cc: @shawnbot

**Comment by mbland** [comment]
Also cc: @barkimedes

**Comment by jmcarp** [comment]
s/add/expand/
https://pages.18f.gov/testing-cookbook/load/

**Comment by mbland** [comment]
Yes. That. Long week.
